apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: stateful
spec:
  serviceName: mariadb
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:11.8
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ghost-secret
                  key: mariadb-root-password
            - name: MYSQL_DATABASE
              value: ghost
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: ghost-secret
                  key: mariadb-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ghost-secret
                  key: mariadb-password
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadb-storage
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-storage
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: stateful
spec:
  ports:
    - port: 3306
  selector:
    app: mariadb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-storage
  namespace: stateful
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi
