apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv0-nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /srv/nfs/shared/mariadb_0
    server: 10.0.2.10
