apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stateless
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 10.0.2.10:5000/imageprocessing-backend:vdm5
        ports:
        - containerPort: 8005
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8005
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8005
          initialDelaySeconds: 10
          periodSeconds: 15
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  namespace: stateless
  labels:
    app: backend
  name: backend
spec:
  ports:
    - port: 8005
      targetPort: 8005
  selector:
    app: backend
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: stateless
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
