apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stateless
  name: image-editor-rembg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-editor-rembg
  template:
    metadata:
      labels:
        app: image-editor-rembg
    spec:
      containers:
      - name: image-editor-rembg
        image: 10.0.2.10:5000/imageprocessing-image-editor-rembg:vdm4
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "1000m"
          limits:
            cpu: "1500m"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 70
          periodSeconds: 15
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  namespace: stateless
  name: image-editor-rembg
spec:
  selector:
    app: image-editor-rembg
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: image-editor-rembg-hpa
  namespace: stateless
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: image-editor-rembg
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
