apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stateless
  name: image-editor-bw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-editor-bw
  template:
    metadata:
      labels:
        app: image-editor-bw
    spec:
      containers:
      - name: image-editor-bw
        image: 10.0.2.10:5000/imageprocessing-image-editor-bw:vdm3
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 15
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  namespace: stateless
  name: image-editor-bw
spec:
  selector:
    app: image-editor-bw
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: image-editor-bw-hpa
  namespace: stateless
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: image-editor-bw
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
