apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: roleBinding-viewer
  namespace: stateless
subjects:
- kind: Group
  name: viewer 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: role-viewer
  apiGroup: rbac.authorization.k8s.io
